kind = "Class"
class_hash = "0x3996edeb67b06bccae720e869f8cbea7653858983bc0be373c890aab7b3ef99"
original_class_hash = "0x3996edeb67b06bccae720e869f8cbea7653858983bc0be373c890aab7b3ef99"
abi = "manifests/dev/abis/base/dojo_world_world.json"
manifest_name = "dojo_world_world"
artifact_name = "dojo::world::world"
