[world]
kind = "WorldContract"
class_hash = "0x3996edeb67b06bccae720e869f8cbea7653858983bc0be373c890aab7b3ef99"
original_class_hash = "0x3996edeb67b06bccae720e869f8cbea7653858983bc0be373c890aab7b3ef99"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x3fe8f0289f1847d6b6b3ef5121d567f4983d649630a603179b68d654e57e8ee"
transaction_hash = "0x43479f7609aad32ed6900acda896c837b227e1ba63e7770daf9bc13a2db4cfd"
block_number = 3
seed = "dojo_examples"
manifest_name = "dojo_world_world"
artifact_name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
manifest_name = "dojo_base_base"
artifact_name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0xffa6a11faac58d9369068074c94e299e374892abf39243fad3712dabb147f"
class_hash = "0x596fa2204bc95f981ac957815aeff2808e774257cba8142e8c6f968c0d8ae4"
original_class_hash = "0x596fa2204bc95f981ac957815aeff2808e774257cba8142e8c6f968c0d8ae4"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples-actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "actions"
namespace = "dojo_examples"
manifest_name = "dojo_examples-actions"
artifact_name = "dojo_examples::actions::actions"

[[contracts]]
kind = "DojoContract"
address = "0x6d3678b1af2e2c700e75c3bcefcb2eb1f8e899f5d366e19a13de0b88c0e7707"
class_hash = "0x7416f8bb5be2b448d8cb5ef6af84e2a9f63f54c68fd3b04537b6a56d3fdbbf9"
original_class_hash = "0x7416f8bb5be2b448d8cb5ef6af84e2a9f63f54c68fd3b04537b6a56d3fdbbf9"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples-mock_token.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "mock_token"
namespace = "dojo_examples"
manifest_name = "dojo_examples-mock_token"
artifact_name = "dojo_examples::mock_token::mock_token"

[[contracts]]
kind = "DojoContract"
address = "0x161d8d912938fa1f85d191216d0bc4e45c90fcdedba5d7eef634dc6286ab8de"
class_hash = "0x3fc738cd153b59715c5c0f3ba57265d86f838610d8926b872b402b74ffaa983"
original_class_hash = "0x3fc738cd153b59715c5c0f3ba57265d86f838610d8926b872b402b74ffaa983"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/dojo_examples-others.json"
reads = []
writes = []
computed = []
init_calldata = [
    "$contract_address:dojo_examples:actions",
    "$class_hash:dojo_examples:actions",
    "10",
]
name = "others"
namespace = "dojo_examples"
manifest_name = "dojo_examples-others"
artifact_name = "dojo_examples::others::others"

[[models]]
kind = "DojoModel"
class_hash = "0x422d29e9d76703627b6e17ec21f76ea51673181cca1db86fe3831e6b9520947"
original_class_hash = "0x422d29e9d76703627b6e17ec21f76ea51673181cca1db86fe3831e6b9520947"
abi = "manifests/dev/abis/deployments/models/dojo_examples-contract_initialized.json"
name = "ContractInitialized"
namespace = "dojo_examples"
manifest_name = "dojo_examples-contract_initialized"
artifact_name = "dojo_examples::others::others::contract_initialized"

[[models.members]]
name = "contract_address"
type = "ContractAddress"
key = true

[[models.members]]
name = "contract_class"
type = "ClassHash"
key = false

[[models.members]]
name = "value"
type = "u8"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x15bb4dfdcfe3dae6ee09cd2912b87f341cb0049c448443c19dff53e1dd2b2e4"
original_class_hash = "0x15bb4dfdcfe3dae6ee09cd2912b87f341cb0049c448443c19dff53e1dd2b2e4"
abi = "manifests/dev/abis/deployments/models/dojo_examples-message.json"
name = "Message"
namespace = "dojo_examples"
manifest_name = "dojo_examples-message"
artifact_name = "dojo_examples::models::message"

[[models.members]]
name = "identity"
type = "ContractAddress"
key = true

[[models.members]]
name = "channel"
type = "felt252"
key = true

[[models.members]]
name = "message"
type = "ByteArray"
key = false

[[models.members]]
name = "salt"
type = "felt252"
key = true

[[models]]
kind = "DojoModel"
class_hash = "0x7b8abdeec63fe60338f5fd160c747c5db5fd911013a1f9c2b15e88900fabc5b"
original_class_hash = "0x7b8abdeec63fe60338f5fd160c747c5db5fd911013a1f9c2b15e88900fabc5b"
abi = "manifests/dev/abis/deployments/models/dojo_examples-mock_token.json"
name = "MockToken"
namespace = "dojo_examples"
manifest_name = "dojo_examples-mock_token"
artifact_name = "dojo_examples::models::mock_token"

[[models.members]]
name = "account"
type = "ContractAddress"
key = true

[[models.members]]
name = "amount"
type = "u128"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1ea2333b6b366988a726f8b95472b38a56506631d916b38a503b57f7dc2c16b"
original_class_hash = "0x1ea2333b6b366988a726f8b95472b38a56506631d916b38a503b57f7dc2c16b"
abi = "manifests/dev/abis/deployments/models/dojo_examples-moved.json"
name = "Moved"
namespace = "dojo_examples"
manifest_name = "dojo_examples-moved"
artifact_name = "dojo_examples::actions::actions::moved"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x276c8225a5addbfe3e6b38d8e288dc977bdce2e2401877c58783d75c61a9f21"
original_class_hash = "0x276c8225a5addbfe3e6b38d8e288dc977bdce2e2401877c58783d75c61a9f21"
abi = "manifests/dev/abis/deployments/models/dojo_examples-moves.json"
name = "Moves"
namespace = "dojo_examples"
manifest_name = "dojo_examples-moves"
artifact_name = "dojo_examples::models::moves"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "remaining"
type = "u8"
key = false

[[models.members]]
name = "last_direction"
type = "Direction"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x1adabc0c605f4cbbad71bbbb86b8da6b964d406103cc854787e627eb779e474"
original_class_hash = "0x1adabc0c605f4cbbad71bbbb86b8da6b964d406103cc854787e627eb779e474"
abi = "manifests/dev/abis/deployments/models/dojo_examples-player_config.json"
name = "PlayerConfig"
namespace = "dojo_examples"
manifest_name = "dojo_examples-player_config"
artifact_name = "dojo_examples::models::player_config"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "name"
type = "ByteArray"
key = false

[[models.members]]
name = "items"
type = "Array<PlayerItem>"
key = false

[[models.members]]
name = "favorite_item"
type = "Option<u32>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xdf544463099a54b4ff5b10473cd62cb56565641d7f6413fe7a499a240f2aac"
original_class_hash = "0xdf544463099a54b4ff5b10473cd62cb56565641d7f6413fe7a499a240f2aac"
abi = "manifests/dev/abis/deployments/models/dojo_examples-position.json"
name = "Position"
namespace = "dojo_examples"
manifest_name = "dojo_examples-position"
artifact_name = "dojo_examples::models::position"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "vec"
type = "Vec2"
key = false
