kind = "DojoContract"
class_hash = "0x596fa2204bc95f981ac957815aeff2808e774257cba8142e8c6f968c0d8ae4"
original_class_hash = "0x596fa2204bc95f981ac957815aeff2808e774257cba8142e8c6f968c0d8ae4"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/dojo_examples-actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "actions"
namespace = "dojo_examples"
manifest_name = "dojo_examples-actions"
artifact_name = "dojo_examples::actions::actions"
